### ISSUE TITLE
Problém s instalací

### ISSUE THREAD

**Issue by Oiri7** [Arcturus-Official/Arcturus-New-Age#2]
Při pokusu o stažení modpacku verze 1.1.4 došlo k přerušení instalace následkem nestažení knihoven viz přiložený screenshot. Můj discord tag je Oiri#5079
![obrazek](https://user-images.githubusercontent.com/86882843/124397697-cdb05500-dd11-11eb-8351-28f2c630feef.png)

**Comment by Avalanche7CZ** [comment]
Máš to broken
